version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_manager
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - NODE_ENV=${NODE_ENV}
      - TZ=Asia/Shanghai
    command: >
      sh -c 'if [ "$$NODE_ENV" = "development" ]; then
               yarn;
               yarn dev;
             else
               yarn start;
             fi'
  redis:
    image: redis:latest
    container_name: redis_manager
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  frontend:
    build: ./frontend
#    ports:
#      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=${NODE_ENV}
      - TZ=Asia/Shanghai
    command: >
      sh -c 'if [ "$$NODE_ENV" = "development" ]; then
               yarn;
               yarn dev;
             else
               yarn start;
             fi'

  nginx:
    image: nginx:latest
    container_name: nginx_manager
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx:/etc/nginx/conf.d

  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "8001:8001"
    environment:
      MINIO_ROOT_USER: admin12345
      MINIO_ROOT_PASSWORD: zhaohao6010
    command: server /data --console-address ":8001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3


volumes:
  mongo-data:
  redis_data:
  minio_data: